name: devnest
description: A smart platform for managing application development teams.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase for backend and database
  supabase_flutter: ^2.5.0
  url_launcher: ^6.2.5
  # For making HTTP requests to Gemini API
  http: ^1.2.0
  lottie: ^3.1.2
  responsive_framework:
  # State management
  provider: ^6.1.2
  flutter_markdown: ^0.7.1 # لتنسيق ردود الذكاء الاصطناعي
  file_picker: ^8.0.0+1
  # supabase_storage: ^0.3.3 # لرفع الملفات إلى Supabase
  flutter_speed_dial: ^7.0.0 
  # Google Fonts for modern UI
  connectivity_plus: ^7.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  # For formatting dates
  intl: ^0.20.2
  flutter_localization:  
  # Icons
  cupertino_icons: ^1.0.2
  # firebase_core:
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  external_path: ^2.2.0
  path_provider:

  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

  # (اختياري ولكن موصى به) لعرض الإشعارات عندما يكون التطبيق مفتوحاً على أندرويد
  flutter_local_notifications: ^17.2.1

  dio: ^5.4.1
  permission_handler: ^12.0.1
  # firebase_messaging:
  open_filex: 
    # file_picker: ^6.2.0
  # path_provider: ^2.1.3
  share_plus: ^12.0.0
  # Add Firebase packages if you proceed with push notifications
  # firebase_core: ^2.27.0
  # firebase_messaging: ^14.7.19
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: 

flutter:
  uses-material-design: true
  
flutter_icons:
  android: true
  image_path: "icon.png"