// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw485YCnIPbuf478KdUOj39hHfiVQDdjA',
    appId: '1:249817694103:web:2e19b3a94903f0b8194ed2',
    messagingSenderId: '249817694103',
    projectId: 'dev-nest-b0b47',
    authDomain: 'dev-nest-b0b47.firebaseapp.com',
    storageBucket: 'dev-nest-b0b47.firebasestorage.app',
    measurementId: 'G-F82SFFH180',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgrXRXqBntl_0uH9zJ6U8gzciQI8VAkuY',
    appId: '1:249817694103:android:ecdf2a5d75071adb194ed2',
    messagingSenderId: '249817694103',
    projectId: 'dev-nest-b0b47',
    storageBucket: 'dev-nest-b0b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSjXgBPXD3B7PSWR-RsQTpPJO1CwND5s',
    appId: '1:249817694103:ios:e28326fc3cab88e4194ed2',
    messagingSenderId: '249817694103',
    projectId: 'dev-nest-b0b47',
    storageBucket: 'dev-nest-b0b47.firebasestorage.app',
    iosBundleId: 'com.example.devnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSjXgBPXD3B7PSWR-RsQTpPJO1CwND5s',
    appId: '1:249817694103:ios:e28326fc3cab88e4194ed2',
    messagingSenderId: '249817694103',
    projectId: 'dev-nest-b0b47',
    storageBucket: 'dev-nest-b0b47.firebasestorage.app',
    iosBundleId: 'com.example.devnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw485YCnIPbuf478KdUOj39hHfiVQDdjA',
    appId: '1:249817694103:web:2d5bb87effe97c2d194ed2',
    messagingSenderId: '249817694103',
    projectId: 'dev-nest-b0b47',
    authDomain: 'dev-nest-b0b47.firebaseapp.com',
    storageBucket: 'dev-nest-b0b47.firebasestorage.app',
    measurementId: 'G-8ZZB4B49NL',
  );
}
